name: zt-mattermost-webhook
on:
  issues:
  issue_comment:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
  pull_request:
    types: [opened, reopened]
  push:
  fork:
  release:
    types: [released]

jobs:
  zt-webhook:
    runs-on: ubuntu-latest
    name: Ziti Mattermost Webhook
    env:
      ZHOOK: ${{ secrets.ZHOOK_URL }}
    steps:
    - uses: hanzozt/zt-mattermost-action-py@v1
      if: env.ZHOOK && github.event_name != 'pull_request_review'
      with:
        ztId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhookUrl: ${{ secrets.ZHOOK_URL_DEV_NOTIFICATIONS }}
        eventJson: ${{ toJson(github.event) }}
        senderUsername: "GitHubZ"
        
    - uses: hanzozt/zt-mattermost-action-py@v1
      if: env.ZHOOK && github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
      with:
        ztId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhookUrl: ${{ secrets.ZHOOK_URL_DEV_NOTIFICATIONS }}
        eventJson: ${{ toJson(github.event) }}
        senderUsername: "GitHubZ"
        
